version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_SCHEMA=nest
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=3600
      - PORT=3000
    depends_on:
      - mongo
      - redis
    networks:
      - local-net

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=nest
    networks:
      - local-net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - local-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 10s

volumes:
  mongo-data:

networks:
  local-net:
    driver: bridge
